# Image: jstubbs/cloudz3sec-tests

FROM jstubbs/cloudz3sec

USER root
COPY requirements-tests.txt .
RUN python -m pip install -r requirements-tests.txt

USER cloudz3sec
COPY tests/__init__.py  /home/cloudz3sec/tests/__init__.py
COPY tests/test_* /home/cloudz3sec/tests/

COPY examples /home/cloudz3sec/examples
WORKDIR /home/cloudz3sec

ENTRYPOINT ["pytest"]
